# 路由，分发请求
zuul:
  routes:
     books:
        url: http://localhost:8090   # 配置路由，可以配置多个，相当于nigux请求转发
     books2:
        url: http://localhost:8099   #books2不存在，只为测试是否可以配置多个路由
# 注册
eureka:
  client:
    serviceUrl:             #注册中心
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/   # 配置两个，两个注册中心相互注册实现高可用
#   给spring 应用起别名
  spring:
    application:
      name: gateway